## Warning: If an item has been removed or renamed, the code may contain error please check careful
## Add items, please enter them in the correct category :)
## Helmet
replaceitem entity @s[hasitem={item=mcpe:army_artic,location=slot.inventory}] slot.armor.head 0 mcpe:army_artic
replaceitem entity @s[hasitem={item=mcpe:army_desert,location=slot.inventory}] slot.armor.head 0 mcpe:army_desert
replaceitem entity @s[hasitem={item=mcpe:army_woodland,location=slot.inventory}] slot.armor.head 0 mcpe:army_woodland
replaceitem entity @s[hasitem={item=mcpe:assault_helmet_black,location=slot.inventory}] slot.armor.head 0 mcpe:assault_helmet_black
replaceitem entity @s[hasitem={item=mcpe:assault_helmet_olive,location=slot.inventory}] slot.armor.head 0 mcpe:assault_helmet_olive
replaceitem entity @s[hasitem={item=mcpe:balaclava_black,location=slot.inventory}] slot.armor.head 0 mcpe:balaclava_black
replaceitem entity @s[hasitem={item=mcpe:ballistic_black,location=slot.inventory}] slot.armor.head 0 mcpe:ballistic_black
replaceitem entity @s[hasitem={item=mcpe:ballistic_green,location=slot.inventory}] slot.armor.head 0 mcpe:ballistic_green
replaceitem entity @s[hasitem={item=mcpe:ballistic_tan,location=slot.inventory}] slot.armor.head 0 mcpe:ballistic_tan
replaceitem entity @s[hasitem={item=mcpe:ballistic_white,location=slot.inventory}] slot.armor.head 0 mcpe:ballistic_white
replaceitem entity @s[hasitem={item=mcpe:bandana_blue,location=slot.inventory}] slot.armor.head 0 mcpe:bandana_blue
replaceitem entity @s[hasitem={item=mcpe:bandana_green,location=slot.inventory}] slot.armor.head 0 mcpe:bandana_green
replaceitem entity @s[hasitem={item=mcpe:bandana_red,location=slot.inventory}] slot.armor.head 0 mcpe:bandana_red
replaceitem entity @s[hasitem={item=mcpe:beanie_black,location=slot.inventory}] slot.armor.head 0 mcpe:beanie_black
replaceitem entity @s[hasitem={item=mcpe:beanie_brown,location=slot.inventory}] slot.armor.head 0 mcpe:beanie_brown
replaceitem entity @s[hasitem={item=mcpe:beanie_olive,location=slot.inventory}] slot.armor.head 0 mcpe:beanie_olive
replaceitem entity @s[hasitem={item=mcpe:beanie_white,location=slot.inventory}] slot.armor.head 0 mcpe:beanie_white
replaceitem entity @s[hasitem={item=mcpe:beret_blue,location=slot.inventory}] slot.armor.head 0 mcpe:beret_blue
replaceitem entity @s[hasitem={item=mcpe:beret_green,location=slot.inventory}] slot.armor.head 0 mcpe:beret_green
replaceitem entity @s[hasitem={item=mcpe:beret_red,location=slot.inventory}] slot.armor.head 0 mcpe:beret_red
replaceitem entity @s[hasitem={item=mcpe:biker_black,location=slot.inventory}] slot.armor.head 0 mcpe:biker_black
replaceitem entity @s[hasitem={item=mcpe:biker_blue,location=slot.inventory}] slot.armor.head 0 mcpe:biker_blue
replaceitem entity @s[hasitem={item=mcpe:biker_red,location=slot.inventory}] slot.armor.head 0 mcpe:biker_red
replaceitem entity @s[hasitem={item=mcpe:biker_white,location=slot.inventory}] slot.armor.head 0 mcpe:biker_white
replaceitem entity @s[hasitem={item=mcpe:biker_yellow,location=slot.inventory}] slot.armor.head 0 mcpe:biker_yellow
replaceitem entity @s[hasitem={item=mcpe:boonie_artic,location=slot.inventory}] slot.armor.head 0 mcpe:boonie_artic
replaceitem entity @s[hasitem={item=mcpe:boonie_black,location=slot.inventory}] slot.armor.head 0 mcpe:boonie_black
replaceitem entity @s[hasitem={item=mcpe:boonie_desert,location=slot.inventory}] slot.armor.head 0 mcpe:boonie_desert
replaceitem entity @s[hasitem={item=mcpe:boonie_green,location=slot.inventory}] slot.armor.head 0 mcpe:boonie_green
replaceitem entity @s[hasitem={item=mcpe:boonie_tan,location=slot.inventory}] slot.armor.head 0 mcpe:boonie_tan
replaceitem entity @s[hasitem={item=mcpe:boonie_woodland,location=slot.inventory}] slot.armor.head 0 mcpe:boonie_woodland
replaceitem entity @s[hasitem={item=mcpe:cap_black,location=slot.inventory}] slot.armor.head 0 mcpe:cap_black
replaceitem entity @s[hasitem={item=mcpe:cap_blue,location=slot.inventory}] slot.armor.head 0 mcpe:cap_blue
replaceitem entity @s[hasitem={item=mcpe:cap_green,location=slot.inventory}] slot.armor.head 0 mcpe:cap_green
replaceitem entity @s[hasitem={item=mcpe:cap_red,location=slot.inventory}] slot.armor.head 0 mcpe:cap_red
replaceitem entity @s[hasitem={item=mcpe:clown_wig,location=slot.inventory}] slot.armor.head 0 mcpe:clown_wig
replaceitem entity @s[hasitem={item=mcpe:cowboy_black,location=slot.inventory}] slot.armor.head 0 mcpe:cowboy_black
replaceitem entity @s[hasitem={item=mcpe:cowboy_brown,location=slot.inventory}] slot.armor.head 0 mcpe:cowboy_brown
replaceitem entity @s[hasitem={item=mcpe:cowboy_white,location=slot.inventory}] slot.armor.head 0 mcpe:cowboy_white
replaceitem entity @s[hasitem={item=mcpe:durag_black,location=slot.inventory}] slot.armor.head 0 mcpe:durag_black
replaceitem entity @s[hasitem={item=mcpe:durag_brown,location=slot.inventory}] slot.armor.head 0 mcpe:durag_brown
replaceitem entity @s[hasitem={item=mcpe:firefighter_hat,location=slot.inventory}] slot.armor.head 0 mcpe:firefighter_hat
replaceitem entity @s[hasitem={item=mcpe:flat_black,location=slot.inventory}] slot.armor.head 0 mcpe:flat_black
replaceitem entity @s[hasitem={item=mcpe:flat_brown,location=slot.inventory}] slot.armor.head 0 mcpe:flat_brown
replaceitem entity @s[hasitem={item=mcpe:gasmask_black,location=slot.inventory}] slot.armor.head 0 mcpe:gasmask_black
replaceitem entity @s[hasitem={item=mcpe:gasmask_tactical,location=slot.inventory}] slot.armor.head 0 mcpe:gasmask_tactical
replaceitem entity @s[hasitem={item=mcpe:gasmask_white,location=slot.inventory}] slot.armor.head 0 mcpe:gasmask_white
replaceitem entity @s[hasitem={item=mcpe:great_helmet,location=slot.inventory}] slot.armor.head 0 mcpe:great_helmet
replaceitem entity @s[hasitem={item=mcpe:hard_blue,location=slot.inventory}] slot.armor.head 0 mcpe:hard_blue
replaceitem entity @s[hasitem={item=mcpe:hard_orange,location=slot.inventory}] slot.armor.head 0 mcpe:hard_orange
replaceitem entity @s[hasitem={item=mcpe:hard_red,location=slot.inventory}] slot.armor.head 0 mcpe:hard_red
replaceitem entity @s[hasitem={item=mcpe:hard_white,location=slot.inventory}] slot.armor.head 0 mcpe:hard_white
replaceitem entity @s[hasitem={item=mcpe:hard_yellow,location=slot.inventory}] slot.armor.head 0 mcpe:hard_yellow
replaceitem entity @s[hasitem={item=mcpe:headlamp,location=slot.inventory}] slot.armor.head 0 mcpe:headlamp
replaceitem entity @s[hasitem={item=mcpe:hunting_hat,location=slot.inventory}] slot.armor.head 0 mcpe:hunting_hat
replaceitem entity @s[hasitem={item=mcpe:maid_bonnet,location=slot.inventory}] slot.armor.head 0 mcpe:maid_bonnet
replaceitem entity @s[hasitem={item=mcpe:mask_fawkes,location=slot.inventory}] slot.armor.head 0 mcpe:mask_fawkes
replaceitem entity @s[hasitem={item=mcpe:mask_funni,location=slot.inventory}] slot.armor.head 0 mcpe:mask_funni
replaceitem entity @s[hasitem={item=mcpe:mask_troll,location=slot.inventory}] slot.armor.head 0 mcpe:mask_troll
replaceitem entity @s[hasitem={item=mcpe:night_goggles,location=slot.inventory}] slot.armor.head 0 mcpe:night_goggles
replaceitem entity @s[hasitem={item=mcpe:peaked_green,location=slot.inventory}] slot.armor.head 0 mcpe:peaked_green
replaceitem entity @s[hasitem={item=mcpe:peaked_tan,location=slot.inventory}] slot.armor.head 0 mcpe:peaked_tan
replaceitem entity @s[hasitem={item=mcpe:peaked_white,location=slot.inventory}] slot.armor.head 0 mcpe:peaked_white
replaceitem entity @s[hasitem={item=mcpe:plague_hat,location=slot.inventory}] slot.armor.head 0 mcpe:plague_hat
replaceitem entity @s[hasitem={item=mcpe:police_hat,location=slot.inventory}] slot.armor.head 0 mcpe:police_hat
replaceitem entity @s[hasitem={item=mcpe:police_riot,location=slot.inventory}] slot.armor.head 0 mcpe:police_riot
replaceitem entity @s[hasitem={item=mcpe:respirator_mask,location=slot.inventory}] slot.armor.head 0 mcpe:respirator_mask
replaceitem entity @s[hasitem={item=mcpe:shemagh_blue,location=slot.inventory}] slot.armor.head 0 mcpe:shemagh_blue
replaceitem entity @s[hasitem={item=mcpe:shemagh_brown,location=slot.inventory}] slot.armor.head 0 mcpe:shemagh_brown
replaceitem entity @s[hasitem={item=mcpe:shemagh_gray,location=slot.inventory}] slot.armor.head 0 mcpe:shemagh_gray
replaceitem entity @s[hasitem={item=mcpe:shemagh_olive,location=slot.inventory}] slot.armor.head 0 mcpe:shemagh_olive
replaceitem entity @s[hasitem={item=mcpe:shemagh_red,location=slot.inventory}] slot.armor.head 0 mcpe:shemagh_red
replaceitem entity @s[hasitem={item=mcpe:shemagh_tan,location=slot.inventory}] slot.armor.head 0 mcpe:shemagh_tan
replaceitem entity @s[hasitem={item=mcpe:skimask_black,location=slot.inventory}] slot.armor.head 0 mcpe:skimask_black
replaceitem entity @s[hasitem={item=mcpe:spec_helmet,location=slot.inventory}] slot.armor.head 0 mcpe:spec_helmet
replaceitem entity @s[hasitem={item=mcpe:tactical_helmet_black,location=slot.inventory}] slot.armor.head 0 mcpe:tactical_helmet_black
replaceitem entity @s[hasitem={item=mcpe:tactical_helmet_olive,location=slot.inventory}] slot.armor.head 0 mcpe:tactical_helmet_olive
replaceitem entity @s[hasitem={item=mcpe:tactical_helmet_tan,location=slot.inventory}] slot.armor.head 0 mcpe:tactical_helmet_tan
replaceitem entity @s[hasitem={item=mcpe:tactical_helmet_white,location=slot.inventory}] slot.armor.head 0 mcpe:tactical_helmet_white
replaceitem entity @s[hasitem={item=mcpe:un_helmet,location=slot.inventory}] slot.armor.head 0 mcpe:un_helmet
replaceitem entity @s[hasitem={item=mcpe:ushanka,location=slot.inventory}] slot.armor.head 0 mcpe:ushanka
replaceitem entity @s[hasitem={item=mcpe:welder_mask,location=slot.inventory}] slot.armor.head 0 mcpe:welder_mask

## Chestplate
replaceitem entity @s[hasitem={item=mcpe:assault_vest_black,location=slot.inventory}] slot.armor.chest 0 mcpe:assault_vest_black
replaceitem entity @s[hasitem={item=mcpe:assault_vest_olive,location=slot.inventory}] slot.armor.chest 0 mcpe:assault_vest_olive
replaceitem entity @s[hasitem={item=mcpe:biker_vest,location=slot.inventory}] slot.armor.chest 0 mcpe:biker_vest
replaceitem entity @s[hasitem={item=mcpe:biker_vest_skull,location=slot.inventory}] slot.armor.chest 0 mcpe:biker_vest_skull
replaceitem entity @s[hasitem={item=mcpe:chest_brown,location=slot.inventory}] slot.armor.chest 0 mcpe:chest_brown
replaceitem entity @s[hasitem={item=mcpe:chest_green,location=slot.inventory}] slot.armor.chest 0 mcpe:chest_green
replaceitem entity @s[hasitem={item=mcpe:chest_navy,location=slot.inventory}] slot.armor.chest 0 mcpe:chest_navy
replaceitem entity @s[hasitem={item=mcpe:chest_tan,location=slot.inventory}] slot.armor.chest 0 mcpe:chest_tan
replaceitem entity @s[hasitem={item=mcpe:chest_white,location=slot.inventory}] slot.armor.chest 0 mcpe:chest_white
replaceitem entity @s[hasitem={item=mcpe:combat_olive,location=slot.inventory}] slot.armor.chest 0 mcpe:combat_olive
replaceitem entity @s[hasitem={item=mcpe:combat_tan,location=slot.inventory}] slot.armor.chest 0 mcpe:combat_tan
replaceitem entity @s[hasitem={item=mcpe:combat_white,location=slot.inventory}] slot.armor.chest 0 mcpe:combat_white
replaceitem entity @s[hasitem={item=mcpe:hunting_brown,location=slot.inventory}] slot.armor.chest 0 mcpe:hunting_brown
replaceitem entity @s[hasitem={item=mcpe:hunting_navy,location=slot.inventory}] slot.armor.chest 0 mcpe:hunting_navy
replaceitem entity @s[hasitem={item=mcpe:plate_vest_gray,location=slot.inventory}] slot.armor.chest 0 mcpe:plate_vest_gray
replaceitem entity @s[hasitem={item=mcpe:plate_vest_olive,location=slot.inventory}] slot.armor.chest 0 mcpe:plate_vest_olive
replaceitem entity @s[hasitem={item=mcpe:plate_vest_tan,location=slot.inventory}] slot.armor.chest 0 mcpe:plate_vest_tan
replaceitem entity @s[hasitem={item=mcpe:plate_vest_white,location=slot.inventory}] slot.armor.chest 0 mcpe:plate_vest_white
replaceitem entity @s[hasitem={item=mcpe:police_vest,location=slot.inventory}] slot.armor.chest 0 mcpe:police_vest
replaceitem entity @s[hasitem={item=mcpe:press_vest,location=slot.inventory}] slot.armor.chest 0 mcpe:press_vest
replaceitem entity @s[hasitem={item=mcpe:reflective_lime,location=slot.inventory}] slot.armor.chest 0 mcpe:reflective_lime
replaceitem entity @s[hasitem={item=mcpe:reflective_orange,location=slot.inventory}] slot.armor.chest 0 mcpe:reflective_orange
replaceitem entity @s[hasitem={item=mcpe:reflective_yellow,location=slot.inventory}] slot.armor.chest 0 mcpe:reflective_yellow
replaceitem entity @s[hasitem={item=mcpe:stab_vest_gray,location=slot.inventory}] slot.armor.chest 0 mcpe:stab_vest_gray
replaceitem entity @s[hasitem={item=mcpe:stab_vest_tan,location=slot.inventory}] slot.armor.chest 0 mcpe:stab_vest_tan
replaceitem entity @s[hasitem={item=mcpe:tactical_vest_black,location=slot.inventory}] slot.armor.chest 0 mcpe:tactical_vest_black
replaceitem entity @s[hasitem={item=mcpe:tactical_vest_olive,location=slot.inventory}] slot.armor.chest 0 mcpe:tactical_vest_olive
replaceitem entity @s[hasitem={item=mcpe:tactical_vest_tan,location=slot.inventory}] slot.armor.chest 0 mcpe:tactical_vest_tan
replaceitem entity @s[hasitem={item=mcpe:tactical_vest_white,location=slot.inventory}] slot.armor.chest 0 mcpe:tactical_vest_white
replaceitem entity @s[hasitem={item=mcpe:webbing_black,location=slot.inventory}] slot.armor.chest 0 mcpe:webbing_black
replaceitem entity @s[hasitem={item=mcpe:webbing_brown,location=slot.inventory}] slot.armor.chest 0 mcpe:webbing_brown
replaceitem entity @s[hasitem={item=mcpe:webbing_green,location=slot.inventory}] slot.armor.chest 0 mcpe:webbing_green
replaceitem entity @s[hasitem={item=mcpe:webbing_tan,location=slot.inventory}] slot.armor.chest 0 mcpe:webbing_tan
replaceitem entity @s[hasitem={item=mcpe:webbing_white,location=slot.inventory}] slot.armor.chest 0 mcpe:webbing_white

## Clothes
replaceitem entity @s[hasitem={item=mcpe:bdu_artic_top,location=slot.inventory}] slot.armor.legs 0 mcpe:bdu_artic_top
replaceitem entity @s[hasitem={item=mcpe:bdu_desert_top,location=slot.inventory}] slot.armor.legs 0 mcpe:bdu_desert_top
replaceitem entity @s[hasitem={item=mcpe:bdu_woodland_top,location=slot.inventory}] slot.armor.legs 0 mcpe:bdu_woodland_top
replaceitem entity @s[hasitem={item=mcpe:chainmail_top,location=slot.inventory}] slot.armor.legs 0 mcpe:chainmail_top
replaceitem entity @s[hasitem={item=mcpe:clown_top,location=slot.inventory}] slot.armor.legs 0 mcpe:clown_top
replaceitem entity @s[hasitem={item=mcpe:crusader_top,location=slot.inventory}] slot.armor.legs 0 mcpe:crusader_top
replaceitem entity @s[hasitem={item=mcpe:firefighter_top,location=slot.inventory}] slot.armor.legs 0 mcpe:firefighter_top
replaceitem entity @s[hasitem={item=mcpe:flannel_blue,location=slot.inventory}] slot.armor.legs 0 mcpe:flannel_blue
replaceitem entity @s[hasitem={item=mcpe:flannel_gray,location=slot.inventory}] slot.armor.legs 0 mcpe:flannel_gray
replaceitem entity @s[hasitem={item=mcpe:flannel_green,location=slot.inventory}] slot.armor.legs 0 mcpe:flannel_green
replaceitem entity @s[hasitem={item=mcpe:flannel_red,location=slot.inventory}] slot.armor.legs 0 mcpe:flannel_red
replaceitem entity @s[hasitem={item=mcpe:flannel_white,location=slot.inventory}] slot.armor.legs 0 mcpe:flannel_white
replaceitem entity @s[hasitem={item=mcpe:ghillie_drygrass_top,location=slot.inventory}] slot.armor.legs 0 mcpe:ghillie_drygrass_top
replaceitem entity @s[hasitem={item=mcpe:ghillie_forest_top,location=slot.inventory}] slot.armor.legs 0 mcpe:ghillie_forest_top
replaceitem entity @s[hasitem={item=mcpe:ghillie_snow_top,location=slot.inventory}] slot.armor.legs 0 mcpe:ghillie_snow_top
replaceitem entity @s[hasitem={item=mcpe:gorka_top,location=slot.inventory}] slot.armor.legs 0 mcpe:gorka_top
replaceitem entity @s[hasitem={item=mcpe:hawaiian_black,location=slot.inventory}] slot.armor.legs 0 mcpe:hawaiian_black
replaceitem entity @s[hasitem={item=mcpe:hawaiian_red,location=slot.inventory}] slot.armor.legs 0 mcpe:hawaiian_red
replaceitem entity @s[hasitem={item=mcpe:hazmat_white_top,location=slot.inventory}] slot.armor.legs 0 mcpe:hazmat_white_top
replaceitem entity @s[hasitem={item=mcpe:hazmat_yellow_top,location=slot.inventory}] slot.armor.legs 0 mcpe:hazmat_yellow_top
replaceitem entity @s[hasitem={item=mcpe:hero_flannel,location=slot.inventory}] slot.armor.legs 0 mcpe:hero_flannel
replaceitem entity @s[hasitem={item=mcpe:hiking_black,location=slot.inventory}] slot.armor.legs 0 mcpe:hiking_black
replaceitem entity @s[hasitem={item=mcpe:hiking_blue,location=slot.inventory}] slot.armor.legs 0 mcpe:hiking_blue
replaceitem entity @s[hasitem={item=mcpe:hoodie_black,location=slot.inventory}] slot.armor.legs 0 mcpe:hoodie_black
replaceitem entity @s[hasitem={item=mcpe:hoodie_blue,location=slot.inventory}] slot.armor.legs 0 mcpe:hoodie_blue
replaceitem entity @s[hasitem={item=mcpe:hoodie_green,location=slot.inventory}] slot.armor.legs 0 mcpe:hoodie_green
replaceitem entity @s[hasitem={item=mcpe:hoodie_red,location=slot.inventory}] slot.armor.legs 0 mcpe:hoodie_red
replaceitem entity @s[hasitem={item=mcpe:hoodie_white,location=slot.inventory}] slot.armor.legs 0 mcpe:hoodie_white
replaceitem entity @s[hasitem={item=mcpe:hoodie_yellow,location=slot.inventory}] slot.armor.legs 0 mcpe:hoodie_yellow
replaceitem entity @s[hasitem={item=mcpe:leather_black,location=slot.inventory}] slot.armor.legs 0 mcpe:leather_black
replaceitem entity @s[hasitem={item=mcpe:leather_brown,location=slot.inventory}] slot.armor.legs 0 mcpe:leather_brown
replaceitem entity @s[hasitem={item=mcpe:maid_top,location=slot.inventory}] slot.armor.legs 0 mcpe:maid_top
replaceitem entity @s[hasitem={item=mcpe:paramedic_top,location=slot.inventory}] slot.armor.legs 0 mcpe:paramedic_top
replaceitem entity @s[hasitem={item=mcpe:plague_top,location=slot.inventory}] slot.armor.legs 0 mcpe:plague_top
replaceitem entity @s[hasitem={item=mcpe:plaid_blue,location=slot.inventory}] slot.armor.legs 0 mcpe:plaid_blue
replaceitem entity @s[hasitem={item=mcpe:plaid_gray,location=slot.inventory}] slot.armor.legs 0 mcpe:plaid_gray
replaceitem entity @s[hasitem={item=mcpe:plaid_olive,location=slot.inventory}] slot.armor.legs 0 mcpe:plaid_olive
replaceitem entity @s[hasitem={item=mcpe:plaid_red,location=slot.inventory}] slot.armor.legs 0 mcpe:plaid_red
replaceitem entity @s[hasitem={item=mcpe:plaid_tan,location=slot.inventory}] slot.armor.legs 0 mcpe:plaid_tan
replaceitem entity @s[hasitem={item=mcpe:plaid_white,location=slot.inventory}] slot.armor.legs 0 mcpe:plaid_white
replaceitem entity @s[hasitem={item=mcpe:police_special_top,location=slot.inventory}] slot.armor.legs 0 mcpe:police_special_top
replaceitem entity @s[hasitem={item=mcpe:police_top,location=slot.inventory}] slot.armor.legs 0 mcpe:police_top
replaceitem entity @s[hasitem={item=mcpe:prisoner_top,location=slot.inventory}] slot.armor.legs 0 mcpe:prisoner_top
replaceitem entity @s[hasitem={item=mcpe:puffer_black,location=slot.inventory}] slot.armor.legs 0 mcpe:puffer_black
replaceitem entity @s[hasitem={item=mcpe:puffer_blue,location=slot.inventory}] slot.armor.legs 0 mcpe:puffer_blue
replaceitem entity @s[hasitem={item=mcpe:special_top,location=slot.inventory}] slot.armor.legs 0 mcpe:special_top
replaceitem entity @s[hasitem={item=mcpe:stripeds_black,location=slot.inventory}] slot.armor.legs 0 mcpe:stripeds_black
replaceitem entity @s[hasitem={item=mcpe:striped_blue,location=slot.inventory}] slot.armor.legs 0 mcpe:striped_blue
replaceitem entity @s[hasitem={item=mcpe:striped_white,location=slot.inventory}] slot.armor.legs 0 mcpe:striped_white
replaceitem entity @s[hasitem={item=mcpe:suede_brown,location=slot.inventory}] slot.armor.legs 0 mcpe:suede_brown
replaceitem entity @s[hasitem={item=mcpe:suit_top_black,location=slot.inventory}] slot.armor.legs 0 mcpe:suit_top_black
replaceitem entity @s[hasitem={item=mcpe:sweater_green,location=slot.inventory}] slot.armor.legs 0 mcpe:sweater_green
replaceitem entity @s[hasitem={item=mcpe:sweater_white,location=slot.inventory}] slot.armor.legs 0 mcpe:sweater_white
replaceitem entity @s[hasitem={item=mcpe:tactical_green,location=slot.inventory}] slot.armor.legs 0 mcpe:tactical_green
replaceitem entity @s[hasitem={item=mcpe:tactical_navy,location=slot.inventory}] slot.armor.legs 0 mcpe:tactical_navy
replaceitem entity @s[hasitem={item=mcpe:tactical_red,location=slot.inventory}] slot.armor.legs 0 mcpe:tactical_red
replaceitem entity @s[hasitem={item=mcpe:tactical_tan,location=slot.inventory}] slot.armor.legs 0 mcpe:tactical_tan
replaceitem entity @s[hasitem={item=mcpe:tactical_white,location=slot.inventory}] slot.armor.legs 0 mcpe:tactical_white
replaceitem entity @s[hasitem={item=mcpe:tracksuit_black,location=slot.inventory}] slot.armor.legs 0 mcpe:tracksuit_black
replaceitem entity @s[hasitem={item=mcpe:tracksuit_blue,location=slot.inventory}] slot.armor.legs 0 mcpe:tracksuit_blue
replaceitem entity @s[hasitem={item=mcpe:tracksuit_red,location=slot.inventory}] slot.armor.legs 0 mcpe:tracksuit_red
replaceitem entity @s[hasitem={item=mcpe:tshirt_black,location=slot.inventory}] slot.armor.legs 0 mcpe:tshirt_black
replaceitem entity @s[hasitem={item=mcpe:tshirt_blue,location=slot.inventory}] slot.armor.legs 0 mcpe:tshirt_blue
replaceitem entity @s[hasitem={item=mcpe:tshirt_green,location=slot.inventory}] slot.armor.legs 0 mcpe:tshirt_green
replaceitem entity @s[hasitem={item=mcpe:tshirt_red,location=slot.inventory}] slot.armor.legs 0 mcpe:tshirt_red
replaceitem entity @s[hasitem={item=mcpe:tshirt_white,location=slot.inventory}] slot.armor.legs 0 mcpe:tshirt_white
replaceitem entity @s[hasitem={item=mcpe:tshirt_yellow,location=slot.inventory}] slot.armor.legs 0 mcpe:tshirt_yellow
replaceitem entity @s[hasitem={item=mcpe:varsity_blue,location=slot.inventory}] slot.armor.legs 0 mcpe:varsity_blue
replaceitem entity @s[hasitem={item=mcpe:varsity_brown,location=slot.inventory}] slot.armor.legs 0 mcpe:varsity_brown
replaceitem entity @s[hasitem={item=mcpe:varsity_green,location=slot.inventory}] slot.armor.legs 0 mcpe:varsity_green
replaceitem entity @s[hasitem={item=mcpe:varsity_red,location=slot.inventory}] slot.armor.legs 0 mcpe:varsity_red

## Pants
replaceitem entity @s[hasitem={item=mcpe:bdu_artic_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:bdu_artic_bottom
replaceitem entity @s[hasitem={item=mcpe:bdu_desert_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:bdu_desert_bottom
replaceitem entity @s[hasitem={item=mcpe:bdu_woodland_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:bdu_woodland_bottom
replaceitem entity @s[hasitem={item=mcpe:cargo_black,location=slot.inventory}] slot.armor.feet 0 mcpe:cargo_black
replaceitem entity @s[hasitem={item=mcpe:cargo_brown,location=slot.inventory}] slot.armor.feet 0 mcpe:cargo_brown
replaceitem entity @s[hasitem={item=mcpe:cargo_green,location=slot.inventory}] slot.armor.feet 0 mcpe:cargo_green
replaceitem entity @s[hasitem={item=mcpe:cargo_tan,location=slot.inventory}] slot.armor.feet 0 mcpe:cargo_tan
replaceitem entity @s[hasitem={item=mcpe:cargo_white,location=slot.inventory}] slot.armor.feet 0 mcpe:cargo_white
replaceitem entity @s[hasitem={item=mcpe:chainmail_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:chainmail_bottom
replaceitem entity @s[hasitem={item=mcpe:clown_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:clown_bottom
replaceitem entity @s[hasitem={item=mcpe:ghillie_drygrass_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:ghillie_drygrass_bottom
replaceitem entity @s[hasitem={item=mcpe:ghillie_forest_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:ghillie_forest_bottom
replaceitem entity @s[hasitem={item=mcpe:ghillie_snow_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:ghillie_snow_bottom
replaceitem entity @s[hasitem={item=mcpe:gorka_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:gorka_bottom
replaceitem entity @s[hasitem={item=mcpe:hazmat_white_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:hazmat_white_bottom
replaceitem entity @s[hasitem={item=mcpe:hazmat_yellow_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:hazmat_yellow_bottom
replaceitem entity @s[hasitem={item=mcpe:jean_black,location=slot.inventory}] slot.armor.feet 0 mcpe:jean_black
replaceitem entity @s[hasitem={item=mcpe:jean_blue,location=slot.inventory}] slot.armor.feet 0 mcpe:jean_blue
replaceitem entity @s[hasitem={item=mcpe:jean_brown,location=slot.inventory}] slot.armor.feet 0 mcpe:jean_brown
replaceitem entity @s[hasitem={item=mcpe:jean_light,location=slot.inventory}] slot.armor.feet 0 mcpe:jean_light
replaceitem entity @s[hasitem={item=mcpe:khaki_light,location=slot.inventory}] slot.armor.feet 0 mcpe:khaki_light
replaceitem entity @s[hasitem={item=mcpe:maid_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:maid_bottom
replaceitem entity @s[hasitem={item=mcpe:overall_black,location=slot.inventory}] slot.armor.feet 0 mcpe:overall_black
replaceitem entity @s[hasitem={item=mcpe:overall_blue,location=slot.inventory}] slot.armor.feet 0 mcpe:overall_blue
replaceitem entity @s[hasitem={item=mcpe:overall_brown,location=slot.inventory}] slot.armor.feet 0 mcpe:overall_brown
replaceitem entity @s[hasitem={item=mcpe:paramedic_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:paramedic_bottom
replaceitem entity @s[hasitem={item=mcpe:plague_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:plague_bottom
replaceitem entity @s[hasitem={item=mcpe:police_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:police_bottom
replaceitem entity @s[hasitem={item=mcpe:police_special_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:police_special_bottom
replaceitem entity @s[hasitem={item=mcpe:prisoner_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:prisoner_bottom
replaceitem entity @s[hasitem={item=mcpe:slack_black,location=slot.inventory}] slot.armor.feet 0 mcpe:slack_black
replaceitem entity @s[hasitem={item=mcpe:special_bottom,location=slot.inventory}] slot.armor.feet 0 mcpe:special_bottom
replaceitem entity @s[hasitem={item=mcpe:suspender_black,location=slot.inventory}] slot.armor.feet 0 mcpe:suspender_black
replaceitem entity @s[hasitem={item=mcpe:trackpants_black,location=slot.inventory}] slot.armor.feet 0 mcpe:trackpants_black
replaceitem entity @s[hasitem={item=mcpe:trackpants_blue,location=slot.inventory}] slot.armor.feet 0 mcpe:trackpants_blue
replaceitem entity @s[hasitem={item=mcpe:trackpants_red,location=slot.inventory}] slot.armor.feet 0 mcpe:trackpants_red