event entity @s[hasitem=[{item=krep:mm5842,quantity=..9},{item=krep:creativeammo,quantity=0}]] reload0
title @s[hasitem=[{item=krep:mm5842,quantity=..9},{item=krep:creativeammo,quantity=0}]] actionbar at least 10 krep:mm5842s
event entity @s[hasitem=[{item=krep:mm5842,quantity=10},{item=krep:creativeammo,quantity=0}]] reload10
event entity @s[hasitem=[{item=krep:mm5842,quantity=11},{item=krep:creativeammo,quantity=0}]] reload11
event entity @s[hasitem=[{item=krep:mm5842,quantity=12},{item=krep:creativeammo,quantity=0}]] reload12
event entity @s[hasitem=[{item=krep:mm5842,quantity=13},{item=krep:creativeammo,quantity=0}]] reload13
event entity @s[hasitem=[{item=krep:mm5842,quantity=14},{item=krep:creativeammo,quantity=0}]] reload14
event entity @s[hasitem=[{item=krep:mm5842,quantity=15},{item=krep:creativeammo,quantity=0}]] reload15
event entity @s[hasitem=[{item=krep:mm5842,quantity=16},{item=krep:creativeammo,quantity=0}]] reload16
event entity @s[hasitem=[{item=krep:mm5842,quantity=17},{item=krep:creativeammo,quantity=0}]] reload17
event entity @s[hasitem=[{item=krep:mm5842,quantity=18},{item=krep:creativeammo,quantity=0}]] reload18
event entity @s[hasitem=[{item=krep:mm5842,quantity=19},{item=krep:creativeammo,quantity=0}]] reload19
event entity @s[hasitem=[{item=krep:mm5842,quantity=20},{item=krep:creativeammo,quantity=0}]] reload20
event entity @s[hasitem=[{item=krep:mm5842,quantity=21},{item=krep:creativeammo,quantity=0}]] reload21
event entity @s[hasitem=[{item=krep:mm5842,quantity=22},{item=krep:creativeammo,quantity=0}]] reload22
event entity @s[hasitem=[{item=krep:mm5842,quantity=23},{item=krep:creativeammo,quantity=0}]] reload23
event entity @s[hasitem=[{item=krep:mm5842,quantity=24},{item=krep:creativeammo,quantity=0}]] reload24
event entity @s[hasitem=[{item=krep:mm5842,quantity=25},{item=krep:creativeammo,quantity=0}]] reload25
event entity @s[hasitem=[{item=krep:mm5842,quantity=26},{item=krep:creativeammo,quantity=0}]] reload26
event entity @s[hasitem=[{item=krep:mm5842,quantity=27},{item=krep:creativeammo,quantity=0}]] reload27
event entity @s[hasitem=[{item=krep:mm5842,quantity=28},{item=krep:creativeammo,quantity=0}]] reload28
event entity @s[hasitem=[{item=krep:mm5842,quantity=29},{item=krep:creativeammo,quantity=0}]] reload29
event entity @s[hasitem=[{item=krep:mm5842,quantity=30},{item=krep:creativeammo,quantity=0}]] reload30
event entity @s[hasitem=[{item=krep:mm5842,quantity=31},{item=krep:creativeammo,quantity=0}]] reload31
event entity @s[hasitem=[{item=krep:mm5842,quantity=32},{item=krep:creativeammo,quantity=0}]] reload32
event entity @s[hasitem=[{item=krep:mm5842,quantity=33},{item=krep:creativeammo,quantity=0}]] reload33
event entity @s[hasitem=[{item=krep:mm5842,quantity=34},{item=krep:creativeammo,quantity=0}]] reload34
event entity @s[hasitem=[{item=krep:mm5842,quantity=35},{item=krep:creativeammo,quantity=0}]] reload35
event entity @s[hasitem=[{item=krep:mm5842,quantity=36},{item=krep:creativeammo,quantity=0}]] reload36
event entity @s[hasitem=[{item=krep:mm5842,quantity=37},{item=krep:creativeammo,quantity=0}]] reload37
event entity @s[hasitem=[{item=krep:mm5842,quantity=38},{item=krep:creativeammo,quantity=0}]] reload38
event entity @s[hasitem=[{item=krep:mm5842,quantity=39},{item=krep:creativeammo,quantity=0}]] reload39
event entity @s[hasitem=[{item=krep:mm5842,quantity=40},{item=krep:creativeammo,quantity=0}]] reload40
event entity @s[hasitem=[{item=krep:mm5842,quantity=41},{item=krep:creativeammo,quantity=0}]] reload41
event entity @s[hasitem=[{item=krep:mm5842,quantity=42},{item=krep:creativeammo,quantity=0}]] reload42
event entity @s[hasitem=[{item=krep:mm5842,quantity=43},{item=krep:creativeammo,quantity=0}]] reload43
event entity @s[hasitem=[{item=krep:mm5842,quantity=44},{item=krep:creativeammo,quantity=0}]] reload44
event entity @s[hasitem=[{item=krep:mm5842,quantity=45},{item=krep:creativeammo,quantity=0}]] reload45
event entity @s[hasitem=[{item=krep:mm5842,quantity=46},{item=krep:creativeammo,quantity=0}]] reload46
event entity @s[hasitem=[{item=krep:mm5842,quantity=47},{item=krep:creativeammo,quantity=0}]] reload47
event entity @s[hasitem=[{item=krep:mm5842,quantity=48},{item=krep:creativeammo,quantity=0}]] reload48
event entity @s[hasitem=[{item=krep:mm5842,quantity=49},{item=krep:creativeammo,quantity=0}]] reload49
event entity @s[hasitem=[{item=krep:mm5842,quantity=50},{item=krep:creativeammo,quantity=0}]] reload50
event entity @s[hasitem=[{item=krep:mm5842,quantity=51},{item=krep:creativeammo,quantity=0}]] reload51
event entity @s[hasitem=[{item=krep:mm5842,quantity=52},{item=krep:creativeammo,quantity=0}]] reload52
event entity @s[hasitem=[{item=krep:mm5842,quantity=53},{item=krep:creativeammo,quantity=0}]] reload53
event entity @s[hasitem=[{item=krep:mm5842,quantity=54},{item=krep:creativeammo,quantity=0}]] reload54
event entity @s[hasitem=[{item=krep:mm5842,quantity=55},{item=krep:creativeammo,quantity=0}]] reload55
event entity @s[hasitem=[{item=krep:mm5842,quantity=56},{item=krep:creativeammo,quantity=0}]] reload56
event entity @s[hasitem=[{item=krep:mm5842,quantity=57},{item=krep:creativeammo,quantity=0}]] reload57
event entity @s[hasitem=[{item=krep:mm5842,quantity=58},{item=krep:creativeammo,quantity=0}]] reload58
event entity @s[hasitem=[{item=krep:mm5842,quantity=59},{item=krep:creativeammo,quantity=0}]] reload59
event entity @s[hasitem=[{item=krep:mm5842,quantity=60},{item=krep:creativeammo,quantity=0}]] reload60
event entity @s[hasitem=[{item=krep:mm5842,quantity=61},{item=krep:creativeammo,quantity=0}]] reload61
event entity @s[hasitem=[{item=krep:mm5842,quantity=62},{item=krep:creativeammo,quantity=0}]] reload62
event entity @s[hasitem=[{item=krep:mm5842,quantity=63},{item=krep:creativeammo,quantity=0}]] reload63
event entity @s[hasitem=[{item=krep:mm5842,quantity=64},{item=krep:creativeammo,quantity=0}]] reload64
event entity @s[hasitem=[{item=krep:mm5842,quantity=65},{item=krep:creativeammo,quantity=0}]] reload65
event entity @s[hasitem=[{item=krep:mm5842,quantity=66},{item=krep:creativeammo,quantity=0}]] reload66
event entity @s[hasitem=[{item=krep:mm5842,quantity=67},{item=krep:creativeammo,quantity=0}]] reload67
event entity @s[hasitem=[{item=krep:mm5842,quantity=68},{item=krep:creativeammo,quantity=0}]] reload68
event entity @s[hasitem=[{item=krep:mm5842,quantity=69},{item=krep:creativeammo,quantity=0}]] reload69
event entity @s[hasitem=[{item=krep:mm5842,quantity=70},{item=krep:creativeammo,quantity=0}]] reload70
event entity @s[hasitem=[{item=krep:mm5842,quantity=71},{item=krep:creativeammo,quantity=0}]] reload71
event entity @s[hasitem=[{item=krep:mm5842,quantity=72},{item=krep:creativeammo,quantity=0}]] reload72
event entity @s[hasitem=[{item=krep:mm5842,quantity=73},{item=krep:creativeammo,quantity=0}]] reload73
event entity @s[hasitem=[{item=krep:mm5842,quantity=74},{item=krep:creativeammo,quantity=0}]] reload74
event entity @s[hasitem=[{item=krep:mm5842,quantity=75},{item=krep:creativeammo,quantity=0}]] reload75
event entity @s[hasitem=[{item=krep:mm5842,quantity=76},{item=krep:creativeammo,quantity=0}]] reload76
event entity @s[hasitem=[{item=krep:mm5842,quantity=77},{item=krep:creativeammo,quantity=0}]] reload77
event entity @s[hasitem=[{item=krep:mm5842,quantity=78},{item=krep:creativeammo,quantity=0}]] reload78
event entity @s[hasitem=[{item=krep:mm5842,quantity=79},{item=krep:creativeammo,quantity=0}]] reload79
event entity @s[hasitem=[{item=krep:mm5842,quantity=80},{item=krep:creativeammo,quantity=0}]] reload80
event entity @s[hasitem=[{item=krep:mm5842,quantity=81},{item=krep:creativeammo,quantity=0}]] reload81
event entity @s[hasitem=[{item=krep:mm5842,quantity=82},{item=krep:creativeammo,quantity=0}]] reload82
event entity @s[hasitem=[{item=krep:mm5842,quantity=83},{item=krep:creativeammo,quantity=0}]] reload83
event entity @s[hasitem=[{item=krep:mm5842,quantity=84},{item=krep:creativeammo,quantity=0}]] reload84
event entity @s[hasitem=[{item=krep:mm5842,quantity=85},{item=krep:creativeammo,quantity=0}]] reload85
event entity @s[hasitem=[{item=krep:mm5842,quantity=86},{item=krep:creativeammo,quantity=0}]] reload86
event entity @s[hasitem=[{item=krep:mm5842,quantity=87},{item=krep:creativeammo,quantity=0}]] reload87
event entity @s[hasitem=[{item=krep:mm5842,quantity=88},{item=krep:creativeammo,quantity=0}]] reload88
event entity @s[hasitem=[{item=krep:mm5842,quantity=89},{item=krep:creativeammo,quantity=0}]] reload89
event entity @s[hasitem=[{item=krep:mm5842,quantity=90},{item=krep:creativeammo,quantity=0}]] reload90
event entity @s[hasitem=[{item=krep:mm5842,quantity=91},{item=krep:creativeammo,quantity=0}]] reload91
event entity @s[hasitem=[{item=krep:mm5842,quantity=92},{item=krep:creativeammo,quantity=0}]] reload92
event entity @s[hasitem=[{item=krep:mm5842,quantity=93},{item=krep:creativeammo,quantity=0}]] reload93
event entity @s[hasitem=[{item=krep:mm5842,quantity=94},{item=krep:creativeammo,quantity=0}]] reload94
event entity @s[hasitem=[{item=krep:mm5842,quantity=95},{item=krep:creativeammo,quantity=0}]] reload95
event entity @s[hasitem=[{item=krep:mm5842,quantity=96},{item=krep:creativeammo,quantity=0}]] reload96
event entity @s[hasitem=[{item=krep:mm5842,quantity=97},{item=krep:creativeammo,quantity=0}]] reload97
event entity @s[hasitem=[{item=krep:mm5842,quantity=98},{item=krep:creativeammo,quantity=0}]] reload98
event entity @s[hasitem=[{item=krep:mm5842,quantity=99},{item=krep:creativeammo,quantity=0}]] reload99
event entity @s[hasitem=[{item=krep:mm5842,quantity=100..},{item=krep:creativeammo,quantity=0}]] reload100
event entity @s[hasitem={item=krep:creativeammo,quantity=1..}] reload100