scoreboard players set @s thirst 20
scoreboard players set @s blood 3500
scoreboard players set @s temperature 11
scoreboard players set @s bleedingTimer 0
scoreboard players set @s infection 0
scoreboard players set @s ammo 31
scoreboard players set @s fuel 20
scoreboard players set @s stamina 20
scoreboard players set @s glock17 15
scoreboard players set @s python 6
scoreboard players set @s m1911 7
scoreboard players set @s l96a1 10
scoreboard players set @s cz527 5
scoreboard players set @s ak47 30
scoreboard players set @s aks74u 30
scoreboard players set @s m4a1 30
scoreboard players set @s fal 20
scoreboard players set @s famas 25
scoreboard players set @s mp5 30
scoreboard players set @s ump45 25
scoreboard players set @s ss1 30
scoreboard players set @s garand 8
scoreboard players set @s l2a3 32
scoreboard players set @s m1014 7
scoreboard players set @s m1897 7
scoreboard players set @s izh43 2
scoreboard players set @s m1894c 10
scoreboard players set @s rpk 75
scoreboard players set @s anaconda 6
scoreboard players set @s m14 20
scoreboard players set @s ak74 30
scoreboard players set @s svd 10
scoreboard players set @s m79 1
scoreboard players set @s sks 10
scoreboard players set @s makarov 8
scoreboard players set @s mosin 5
scoreboard players set @s vz65 20
scoreboard players set @s m16a1 30
scoreboard players set @s makarov_pb 8
scoreboard players set @s m870 8
scoreboard players set @s asval 20