scoreboard objectives add ammo dummy ammo
scoreboard objectives add blood dummy blood
scoreboard objectives add temperature dummy temperature
scoreboard objectives add bleedingTimer dummy bleedingTimer
scoreboard objectives add infection dummy infection
scoreboard objectives add thirst dummy thirst
scoreboard objectives add stamina dummy stamina
scoreboard objectives add broken_bones dummy broken_bones
scoreboard objectives add fuel dummy fuel

scoreboard objectives add python dummy python
scoreboard objectives add glock17 dummy glock17
scoreboard objectives add m1911 dummy m1911
scoreboard objectives add l96a1 dummy l96a1
scoreboard objectives add cz527 dummy cz527
scoreboard objectives add ak47 dummy ak47
scoreboard objectives add aks74u dummy aks74u
scoreboard objectives add fal dummy fal
scoreboard objectives add garand dummy garand
scoreboard objectives add famas dummy famas
scoreboard objectives add m4a1 dummy m4a1
scoreboard objectives add ump45 dummy ump45
scoreboard objectives add mp5 dummy mp5
scoreboard objectives add ss1 dummy ss1
scoreboard objectives add l2a3 dummy l2a3
scoreboard objectives add m1014 dummy m1014
scoreboard objectives add m1897 dummy m1897
scoreboard objectives add izh43 dummy izh43
scoreboard objectives add m1894c dummy m1894c
scoreboard objectives add rpk dummy rpk
scoreboard objectives add anaconda dummy anaconda
scoreboard objectives add m14 dummy m14
scoreboard objectives add ak74 dummy ak74
scoreboard objectives add svd dummy svd
scoreboard objectives add m79 dummy m79
scoreboard objectives add sks dummy sks
scoreboard objectives add makarov dummy makarov
scoreboard objectives add mosin dummy mosin
scoreboard objectives add vz65 dummy vz65
scoreboard objectives add m16a1 dummy m16a1
scoreboard objectives add makarov_pb dummy makarov_pb
scoreboard objectives add m870 dummy m870
scoreboard objectives add asval dummy asval